// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osfeoyycpsxllexayuor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZmVveXljcHN4bGxleGF5dW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0OTc4NTksImV4cCI6MjA3NDA3Mzg1OX0.wnujXFN-kuDDMABMAKi-wq5mgKYJWOqMB1b4U1VlPFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});